### ISSUE TITLE
Option fix: true not working on 2.1.1

### ISSUE THREAD

**Issue by smoothdvd** [webpack-contrib/eslint-loader#248] opened 2018-09-20 13:58 UTC
```
     {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter'),
          fix: true
        }
      },
```

restore to 2.1.0 works again.
I use eslint-loader with webpack 3.11

**Comment by B2o5T** [comment] 2018-09-23 15:55
+1 thank you man ;) yesterday was the first day when I connected eslint-loader to Webpack and I thought that --fix does not work as expected

**Comment by qqw78901** [comment] 2018-09-25 12:28
+1. it doesn't work in 2.1.1 , webpack 4.10
it seems that the lint configuration didn't take effect even though i use specify the configuration file path with "configFile".
restore to 2.0.0 works again.

`    {
        test: /\.js$/,
        use: [{
            loader: 'babel-loader'
        }, {
            loader: "eslint-loader",
            options: {
                fix: true,
                configFile: path.join(__dirname, '/.eslintrc'),
                emitWarning: true,
                 outputReport: {
                                    filePath: 'eslint-report.html',
                                    formatter: require('eslint/lib/formatters/html')
                }
            }
        }],
        exclude: /node_modules/
    },`

**Comment by Peter-Van-Drunen** [comment] 2018-09-26 15:00
I can also confirm that this issue is effecting me on v2.1.1 and that reverting back to v2.1.0 fixed the problem. The lint config file is getting picked up but the fix option seems to be ignored.

webpack: 4.20.2
webpack-cli: 3.1.1

**Comment by virtualstyle** [comment] 2018-10-03 19:31
This issue started happening on my project recently, but not v2.1.1, I'm using 2.1.0, and it has worked fine all along, but now, while it lints and stops the build for errors/displays warnings and errors, it does not auto fix issues any longer.

**Comment by electricsam** [comment] 2018-10-07 18:39
Confirming.  Autofix worked in v2.1.0, but after upgrading to 2.1.1, it no longer works.  Reverting back to 2.1.0, resolves the issue.

**Comment by brucebinary** [comment] 2018-10-18 03:17
I'm also facing this issue. Using Webpack 4.21.0, webpack-cli 3.1.2.

**Comment by scriptify** [comment] 2018-11-23 10:09
Had a similar issue using eslint-loader@2.1.1 with webpack@4.26.0: It seemed that the configuration file didn't take effect, autofix wasn't working either. Reverting to version 2.1.0 fixed the issue in my case.

**Comment by dstarosta** [comment] 2019-01-07 22:12
When is this issue going to be fixed?

**Comment by qzminski** [comment] 2019-01-18 16:01
Any news on this?

**Comment by ThomasKientz** [comment] 2019-01-25 00:08
I have contacted @MoOx , this package is not maintained anymore :

https://github.com/webpack-contrib/eslint-loader/issues/264

**Comment by aij** [comment] 2019-02-26 14:14
This seems to be fixed in 2.1.2. (At least for me with eslint 5.6.1 and webpack 4.16.1.)

**Comment by waghcwb** [comment] 2019-02-26 22:12
@aij,

I've tested `v2.1.2` and still not working. I'm using `nuxt@2.3.4`

**Comment by bnbarak** [comment] 2019-05-03 19:53
Any update on the issue please?

**Comment by ishpartko** [comment] 2019-06-03 06:32
+1 how to set it?

**Comment by ricardogobbosouza** [comment] 2019-07-04 15:01
Anyone with this problem in version `2.2.1` ?

**Closed** 2019-07-04 23:28 UTC

**Comment by Connum** [comment] 2020-01-28 08:30
Another half a year has passed, the issue is closed, but here I am:

**package.json**
```
"eslint": "^6.8.0",
"eslint-import-resolver-webpack": "^0.12.1",
"eslint-loader": "^3.0.3",
"eslint-plugin-import": "^2.20.0",
"webpack": "^4.41.5",
"webpack-cli": "^3.3.10"
```

**webpack.config.js**
```
{
  test: /\.js$/,
  exclude: /node_modules/,
  loader: "eslint-loader",
  options: {
    fix: true
  }
},
```

`4:1  ×  Expected indentation of 2 spaces   indentation`

It should be able to fix indentation automatically, shoudln't it? Am I doing something wrong?

**Comment by ricardogobbosouza** [comment] 2020-01-28 17:05
Hi @Connum 
Can you share your eslint rules `eslintrc.js` ?

**Comment by Connum** [comment] 2020-02-03 15:38
Sorry for the delay in my answering, @ricardogobbosouza !
Here's my `.eslintrc` file:

```
{
	"parser": "babel-eslint",
	"extends": "airbnb/base",
	"env": {
		"browser": true
	},
	"rules": {
		"comma-dangle": [
			"error",
			"only-multiline"
		],
		"no-plusplus": [
			2,
			{
				"allowForLoopAfterthoughts": true
			}
		]
	},
	"settings": {
		"import/resolver": {
			"webpack": {
				"config": "webpack.config.js"
			}
		}
	}
}
```

**Comment by ricardogobbosouza** [comment] 2020-02-07 00:34
@Connum I was unable to reproduce the problem.
Please provide a repository and step by step to reproduce.
