### ISSUE TITLE
eslint-loader does not use existing eslintrc configuration by default

### ISSUE THREAD

**Issue by thasmo** [webpack-contrib/eslint-loader#269] opened 2019-04-20 17:56 UTC
Using `eslint-loader` does not seem to pick up `.eslintrc` configuration files automatically, which is basically what makes `eslint` configuration a breeze.

I guess this is a bug, because `eslint` itself finds configuration files automatically by traversing the directory structure.

In my case I can not hardcode the path to the `.eslintrc` configuration file.

**Comment by gkrinc** [comment] 2019-05-06 14:44
I think we're having the same problem.

```
"scripts": {
    "build": "webpack -p --config ./webpack.config.js",
    "lint": "./node_modules/.bin/eslint ./src --ext js,jsx",
    ...
}
```

If I run `npm run lint` I get errors, but no errors when I run `npm run build`.

```
module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'eslint-loader',
          },
        ],
      },
     ...
```

I tried adding `configFile` as well and the build still succeeds

```
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'eslint-loader',
            options: {
              configFile: '.eslintrc.json',
            }
          },
        ],
      },
      ...
```

**Comment by paul-mesnilgrente** [comment] 2019-07-03 10:57
Same problem here, I don't know where to start.

**Comment by ricardogobbosouza** [comment] 2019-07-05 00:09
@thasmo 
I could not reproduce
Does this still occur with the latest versions?

**Comment by paul-mesnilgrente** [comment] 2019-07-05 01:18
No, this issue was related to the eslint version 6 support which has been handled in the last 2 versions of eslint-loader (2.2.0 and 2.2.1). I think this issue can be closed.

**Comment by evilebottnawi** [comment] 2019-07-05 10:25
We use official eslint api, maybe something wrong in configuration or setup

**Comment by ricardogobbosouza** [comment] 2019-07-10 12:26
I'm closing,
If necessary reopen please

**Closed by ricardogobbosouza** 2019-07-10 12:26 UTC

**Comment by 6XGate** [comment] 2019-08-19 02:52
I'm running into the same issue, or rather an issue where no errors get picked up at all through webpack.

**Comment by ricardogobbosouza** [comment] 2019-08-19 11:04
@6XGate Could you provide a repository with the issue please ? I'll take a look ;)

**Comment by KarmaBlackshaw** [comment] 2020-04-01 02:25
Has anyone looked into this issue? Having similar problems right now.

```
 module: {
      rules: [
        {
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/,
          options: {
            fix: true
          }
        }
      ]
    },
```

**Comment by denvasden** [comment] 2020-04-15 11:18
@KarmaBlackshaw 
Hey, removing "node_modules" and installing again worked for me.
I know it's weird but true.

**Comment by KarmaBlackshaw** [comment] 2020-04-15 11:52
> @KarmaBlackshaw 
> Hey, removing "node_modules" and installing again worked for me.
> I know it's weird but true.

thankss! I also did that but turns out, my problem was just that my code wasnt included in the build so eslint loader didn't check it.

**Comment by miracle2k** [comment] 2020-05-07 09:56
Deleting `./node_modules/.cache` worked for me.
